{"name": "Проверка создания пользователя, который уже зарегистрирован", "status": "passed", "description": "Создаем пользователя, который уже зарегистрирован. Получаем сообщение об ошибке \"User already exists\" и код 403", "start": 1720953940690, "stop": 1720953940893, "uuid": "7bc62d10-83c5-44d6-877e-fe2dcd55c1b4", "historyId": "ba0431930a610588ee29952cca328eed", "testCaseId": "ba0431930a610588ee29952cca328eed", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_double", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "MBAirDmitry.local"}, {"name": "thread", "value": "73907-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}